const senu =
  "Vegetarian|Chronic pancreatitis, Psychosis|Buttered popcorn, Poutine, Chicken parm, Parma ham, Champ, Lobster, Rendang~Vegan|Catarrh, Heart attack, Itching|Masala dosa, Tacos, Hummus, Goi cuon, Lasagna, Pastel de nata, Chicken muamba~Halal|Anorexia nervosa, Discoid eczema, Kidney stones|Potato chips, Buttered toast with Marmite, Chili crab, Pho, Poke, Pierogi, Tom yum goong~Kosher|Epilepsy, Ewing sarcoma: Children, Bone cancer|Seafood paella, Stinky tofu, Maple syrup, Lechón, Croissant, Donuts, Penang assam laksa~Jain|Non-Hodgkin lymphoma, Haemorrhoids, Reactive arthritis|Som tam, Marzipan, Fish n chips, Fajitas, Arepas, Corn on the cob, Hamburger~Gluten-free|Germ cell tumours, Lipoedema, Angina|Chicken rice, French toast, Ankimo, Butter garlic crab, Shish kebab, Piri-piri chicken, Peking duck~Lactose intolerant|Scoliosis, Cough, Kidney cancer|Poutine, Chicken parm, Parma ham, Champ, Lobster, Rendang, Sushi~Paleo|Cold sore, Skin rashes in children, Thyroid cancer|Tacos, Hummus, Goi cuon, Lasagna, Pastel de nata, Chicken muamba, Chocolate~Raw food|Motor neurone disease, Congenital heart disease, Chlamydia|Buttered toast with Marmite, Chili crab, Pho, Poke, Pierogi, Tom yum goong, Neapolitan pizza~Keto|Fever in children, Anaemia, Allergies|Stinky tofu, Maple syrup, Lechón, Croissant, Donuts, Penang assam laksa, Massaman curry~Dairy-free|Acute myeloid leukaemia, Lung cancer, Testicular cancer|Marzipan, Fish n chips, Fajitas, Arepas, Corn on the cob, Hamburger~Low carb|Peripheral neuropathy, Liver tumours, Polycystic ovary syndrome|French toast, Ankimo, Butter garlic crab, Shish kebab, Piri-piri chicken, Peking duck";

const smed =
  "Chronic pancreatitis, Psychosis|Constipated|Emtricitabine, L-glutamine, Prednisone, Amifostine, Probenecid, Meperidine~Catarrh, Heart attack~Chronic pancreatitis, Psychosis|Not eaten for four days|Emtricitabine, L-glutamine, Prednisone, Amifostine, Probenecid, Meperidine~Catarrh, Heart attack|Not eaten whole day|Deferasirox, Propoxyphene, Amphotericin B, Maraviroc, Dexamethasone, Topotecan~Anorexia nervosa, Discoid eczema|Breaksfast not taken yet|Sirolimus, Thiotepa, Didanosine, Bosentan, Efavirenz, Sunitinib~Epilepsy, Ewing sarcoma: Children|Lunch not taken yet|Factor VIII, Gabapentin, Linezolid, Magnesium, Teniposide, Alemtuzumab~Non-Hodgkin lymphoma, Haemorrhoids|Dinner not taken yet|Ampicillin, Amlodipine, Granisetron, Lopinavir, Interferon alfa-2b, Aminocaproic acid~Germ cell tumours, Lipoedema|Breaksfast just done|Elvitegravir, Cefixime, Allopurinol, Cisplatin, Methotrexate, Promethazine~Scoliosis, Cough|Lunch just done|Phenobarbital, Paclitaxel, Temozolomide, Oxycodone, Thioguanine, Lomustine~Cold sore, Skin rashes in children|Dinner just done|Pegfilgrastim, Phosphorus, Procarbazine, Ifosfamide, Famotidine, Mycophenolate mofetil~Motor neurone disease, Congenital heart disease|Heavy breaksfast done|Labetalol, Dapsone, Abacavir, Sorafenib, Vincristine, Melphalan~Fever in children, Acute pancreatitis|Heavy lunch done|Clofarabine, Dopamine, Lorazepam, Carboplatin, Gemtuzumab ozogamicin, Hydralazine~Acute myeloid leukaemia, Lung cancer|Heavy dinner done|Tacrolimus, Cyclobenzaprine, Hydrocortisone, Lorlatinib, Diclofenac, Pentamidine~Peripheral neuropathy, Liver tumours|Constipated|Trimethoprim, Micafungin, Emtricitabine, Cyproheptadine, Fludarabine, Imatinib";

const stax =
  "USA State of Wisconsin|Capital gains tax|What is the minimum rate?~USA State of Oklahoma|Use tax|What is exempt?~Country of Sudan|Wealth tax|What is the revenue?~California Orange County City of La Palma|Motor fuel tax|How do they report?~USA State of Texas|Tangible personal property tax|How to report it?~USA State of Delaware|Sales tax|What is the maximum rate?~Country of Barbados|Estate and inheritance tax|Is it there?~California Orange County City of Anaheim|Communication services tax|Where to file it?~USA State of Alabama|Stamp duty tax|When is it paid?~Country of Ukraine|Property tax|How many people report it?";

const slla =
  "0|Vegetarian|Chronic pancreatitis, Psychosis|Buttered popcorn, Poutine, Chicken parm, Parma ham, Champ, Lobster, Rendang~1|Chronic pancreatitis, Psychosis|Constipated|Emtricitabine, L-glutamine, Prednisone, Amifostine, Probenecid, Meperidine~2|USA State of Wisconsin|Capital gains tax|What is the minimum rate?~0|Vegan|Catarrh, Heart attack, Itching|Masala dosa, Tacos, Hummus, Goi cuon, Lasagna, Pastel de nata, Chicken muamba~1|Chronic pancreatitis, Psychosis|Not eaten for four days|Emtricitabine, L-glutamine, Prednisone, Amifostine, Probenecid, Meperidine~2|Country of Sudan|Wealth tax|What is the revenue?~0|Kosher|Epilepsy, Ewing sarcoma: Children, Bone cancer|Seafood paella, Stinky tofu, Maple syrup, Lechón, Croissant, Donuts, Penang assam laksa~1|Catarrh, Heart attack|Not eaten whole day|Deferasirox, Propoxyphene, Amphotericin B, Maraviroc, Dexamethasone, Topotecan~2|California Orange County City of La Palma|Motor fuel tax|How do they report?~1|Jain|Non-Hodgkin lymphoma, Haemorrhoids, Reactive arthritis|Som tam, Marzipan, Fish n chips, Fajitas, Arepas, Corn on the cob, Hamburger~1|Anorexia nervosa, Discoid eczema|Breaksfast not taken yet|Sirolimus, Thiotepa, Didanosine, Bosentan, Efavirenz, Sunitinib~2|USA State of Texas|Tangible personal property tax|How to report it?";
